name: Build dylib

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Theos einrichten
      - name: Set up Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "export THEOS=$HOME/theos" >> $GITHUB_ENV

      # 3. .dylib bauen
      - name: Build .dylib
        run: |
          export THEOS=$HOME/theos
          make
          ls -l  # Alle Dateien im Verzeichnis auflisten, damit wir sehen können, welche erstellt wurden

      # 4. Sicherstellen, dass .dylib tatsächlich existiert
      - name: Verify .dylib existence
        run: |
          if [ ! -f "./WarzoneHack.dylib" ]; then
            echo "Fehler: WarzoneHack.dylib wurde nicht gefunden!"
            exit 1
          fi
          echo "WarzoneHack.dylib wurde erfolgreich erstellt."

      # 5. Artefakt hochladen
      - name: Upload dylib
        uses: actions/upload-artifact@v2
        with:
          name: WarzoneHack
          path: ./WarzoneHack.dylib
